//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 계정정보를 변경하던중 예상치않은 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_ACCOUNT_CHANGE_ERROR {
            get {
                return ResourceManager.GetString("MSG_ACCOUNT_CHANGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 계정정보를 정확히 변경하였습니다..
        /// </summary>
        internal static string MSG_ACCOUNT_CHANGE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_ACCOUNT_CHANGE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 계정등록중 예상치않은 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_ACCOUNT_REG_ERROR {
            get {
                return ResourceManager.GetString("MSG_ACCOUNT_REG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정확히 등록되였습니다..
        /// </summary>
        internal static string MSG_ACCOUNT_REG_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_ACCOUNT_REG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 최고관리자만 접근가능합니다..
        /// </summary>
        internal static string MSG_ADMIN_ACCESSABLE {
            get {
                return ResourceManager.GetString("MSG_ADMIN_ACCESSABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 최고관리자만 접근가능합니다..
        /// </summary>
        internal static string MSG_ADMIN_ACEPT_ONLY {
            get {
                return ResourceManager.GetString("MSG_ADMIN_ACEPT_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 전체 리스트.
        /// </summary>
        internal static string MSG_ALL_LIST {
            get {
                return ResourceManager.GetString("MSG_ALL_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 적용 가능한 기기 수를 확인해주세요..
        /// </summary>
        internal static string MSG_APPLY_COUNT_CONFIRM {
            get {
                return ResourceManager.GetString("MSG_APPLY_COUNT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정말 발급 하시겠습니까?.
        /// </summary>
        internal static string MSG_AUTH_REALLY {
            get {
                return ResourceManager.GetString("MSG_AUTH_REALLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택한 배너가 활성화되었습니다..
        /// </summary>
        internal static string MSG_BANNER_ACTIVATED {
            get {
                return ResourceManager.GetString("MSG_BANNER_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 배너를 정확히 추가하였습니다..
        /// </summary>
        internal static string MSG_BANNER_ADD_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_BANNER_ADD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 배너는 최대 3개까지만 등록가능합니다..
        /// </summary>
        internal static string MSG_BANNER_ADD_WARNING {
            get {
                return ResourceManager.GetString("MSG_BANNER_ADD_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 배너삭제중 예상치않은 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_BANNER_DELETE_ERROR {
            get {
                return ResourceManager.GetString("MSG_BANNER_DELETE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록된 배너 조회중 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_BANNER_INFO_ERROR {
            get {
                return ResourceManager.GetString("MSG_BANNER_INFO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택한 배너가 비활성화되었습니다..
        /// </summary>
        internal static string MSG_BANNER_NO_ACTIVATED {
            get {
                return ResourceManager.GetString("MSG_BANNER_NO_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 배너이미지 등록과정에 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_BANNER_REG_ERROR {
            get {
                return ResourceManager.GetString("MSG_BANNER_REG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 수정할 데이터가 존재하지 않습니다..
        /// </summary>
        internal static string MSG_CHANGE_DATA_NO_EXIST {
            get {
                return ResourceManager.GetString("MSG_CHANGE_DATA_NO_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택한 배너 수정과정에 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_CHANGE_ERROR {
            get {
                return ResourceManager.GetString("MSG_CHANGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 체크된 리스트.
        /// </summary>
        internal static string MSG_CHECKED_LIST {
            get {
                return ResourceManager.GetString("MSG_CHECKED_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 환경설정과정에 예상치않은 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_CONFIG_SET_ERROR {
            get {
                return ResourceManager.GetString("MSG_CONFIG_SET_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정확히 설정하였습니다..
        /// </summary>
        internal static string MSG_CONFIG_SET_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_CONFIG_SET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정확히 확인 하신 후 &amp;lt;예&amp;gt;버튼을 눌러주세요.&lt;br&gt;취소하시려면 &amp;lt;아니&amp;gt;버튼을 눌러주세요..
        /// </summary>
        internal static string MSG_CONFIRM_DESCRIPTION {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터추가.
        /// </summary>
        internal static string MSG_DATA_ADD {
            get {
                return ResourceManager.GetString("MSG_DATA_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터가 이미 등록되어 있습니다..
        /// </summary>
        internal static string MSG_DATA_ALREADY_REG {
            get {
                return ResourceManager.GetString("MSG_DATA_ALREADY_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터수정.
        /// </summary>
        internal static string MSG_DATA_CHANGE {
            get {
                return ResourceManager.GetString("MSG_DATA_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터 수정과정에 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_DATA_CHANGE_ERROR {
            get {
                return ResourceManager.GetString("MSG_DATA_CHANGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터를 정확히 수정하였습니다..
        /// </summary>
        internal static string MSG_DATA_CHANGE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_DATA_CHANGE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 삭제할 데이터를 선택해주십시오..
        /// </summary>
        internal static string MSG_DATA_DELETE_CHECK {
            get {
                return ResourceManager.GetString("MSG_DATA_DELETE_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터삭제중 예상치않은 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_DATA_DELETE_ERROR {
            get {
                return ResourceManager.GetString("MSG_DATA_DELETE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택한 데이터가 정확히 삭제되었습니다. &lt;br&gt;&lt;br&gt;.
        /// </summary>
        internal static string MSG_DATA_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_DATA_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터정보 조회중 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_DATA_INFO_ERROR {
            get {
                return ResourceManager.GetString("MSG_DATA_INFO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터 등록과정에 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_DATA_REG_ERROR {
            get {
                return ResourceManager.GetString("MSG_DATA_REG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터를 정확히 등록하였습니다..
        /// </summary>
        internal static string MSG_DATA_REG_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_DATA_REG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정말 삭제 하시겠습니까?.
        /// </summary>
        internal static string MSG_DELETE_REALLY {
            get {
                return ResourceManager.GetString("MSG_DELETE_REALLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 해당 디바이스가 활성화 되었습니다..
        /// </summary>
        internal static string MSG_DEVICE_ACTIVATED {
            get {
                return ResourceManager.GetString("MSG_DEVICE_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 해당 디바이스가 비활성화 되었습니다..
        /// </summary>
        internal static string MSG_DEVICE_NO_ACTIVATED {
            get {
                return ResourceManager.GetString("MSG_DEVICE_NO_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 적용할 디바이스가 존재하지 않습니다..
        /// </summary>
        internal static string MSG_DEVICE_NO_EXIST {
            get {
                return ResourceManager.GetString("MSG_DEVICE_NO_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 등록된 아이디입니다..
        /// </summary>
        internal static string MSG_EXIST_LOGINID {
            get {
                return ResourceManager.GetString("MSG_EXIST_LOGINID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록자명이 중복되였습니다..
        /// </summary>
        internal static string MSG_EXIST_NICKNAME {
            get {
                return ResourceManager.GetString("MSG_EXIST_NICKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 파일형식이 바르지 않습니다..
        /// </summary>
        internal static string MSG_FILE_FORMAT_ERROR {
            get {
                return ResourceManager.GetString("MSG_FILE_FORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터파일 업로드과정에 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_FILE_REG_ERROR {
            get {
                return ResourceManager.GetString("MSG_FILE_REG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100MB 이하의 파일만 업로드가능합니다..
        /// </summary>
        internal static string MSG_FILE_SIZE_ERROR {
            get {
                return ResourceManager.GetString("MSG_FILE_SIZE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5MB 이하의 파일만 업로드가능합니다..
        /// </summary>
        internal static string MSG_FILE_SIZE_ERROR_5 {
            get {
                return ResourceManager.GetString("MSG_FILE_SIZE_ERROR_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 가로 512픽셀이하 이미지만 업로드가능합니다..
        /// </summary>
        internal static string MSG_FILE_SIZE_ERROR_512 {
            get {
                return ResourceManager.GetString("MSG_FILE_SIZE_ERROR_512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 세로 910픽셀이하 이미지만 업로드가능합니다..
        /// </summary>
        internal static string MSG_FILE_SIZE_ERROR_910 {
            get {
                return ResourceManager.GetString("MSG_FILE_SIZE_ERROR_910", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 배너이미지를 입력해주십시오..
        /// </summary>
        internal static string MSG_INPUT_BANNER_IMAGE {
            get {
                return ResourceManager.GetString("MSG_INPUT_BANNER_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 배너링크를 입력해주십시오..
        /// </summary>
        internal static string MSG_INPUT_BANNER_LINK {
            get {
                return ResourceManager.GetString("MSG_INPUT_BANNER_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 배너명을 입력해주십시오..
        /// </summary>
        internal static string MSG_INPUT_BANNER_NAME {
            get {
                return ResourceManager.GetString("MSG_INPUT_BANNER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 변경할 패스워드를 입력하십시오..
        /// </summary>
        internal static string MSG_INPUT_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_INPUT_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터식별코드를 입력해 주십시오..
        /// </summary>
        internal static string MSG_INPUT_DATA_ID {
            get {
                return ResourceManager.GetString("MSG_INPUT_DATA_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터링크를 등록해 주십시오..
        /// </summary>
        internal static string MSG_INPUT_DATA_LINK {
            get {
                return ResourceManager.GetString("MSG_INPUT_DATA_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터버전을 입력해 주십시오..
        /// </summary>
        internal static string MSG_INPUT_DATA_VERSION {
            get {
                return ResourceManager.GetString("MSG_INPUT_DATA_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록자ID를 입력하십시오..
        /// </summary>
        internal static string MSG_INPUT_LOGINID {
            get {
                return ResourceManager.GetString("MSG_INPUT_LOGINID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메시지 내용을 입력해주십시오..
        /// </summary>
        internal static string MSG_INPUT_MESSAGE_CONTENT {
            get {
                return ResourceManager.GetString("MSG_INPUT_MESSAGE_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메시지 타이틀을 입력해주십시오..
        /// </summary>
        internal static string MSG_INPUT_MESSAGE_TITLE {
            get {
                return ResourceManager.GetString("MSG_INPUT_MESSAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록자명을 입력하십시오..
        /// </summary>
        internal static string MSG_INPUT_NICKNAME {
            get {
                return ResourceManager.GetString("MSG_INPUT_NICKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 패스워드를 입력하십시오..
        /// </summary>
        internal static string MSG_INPUT_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_INPUT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인 패스워드를 입력하십시오..
        /// </summary>
        internal static string MSG_INPUT_PASSWORD_CONFIRM {
            get {
                return ResourceManager.GetString("MSG_INPUT_PASSWORD_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 입력하신 패스워드가 일치하지 않습니다..
        /// </summary>
        internal static string MSG_INPUT_PASSWORD_ERROR {
            get {
                return ResourceManager.GetString("MSG_INPUT_PASSWORD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 날짜범위을 정확히 입력해주십시오..
        /// </summary>
        internal static string MSG_INPUT_SEARCH_DATESCALE {
            get {
                return ResourceManager.GetString("MSG_INPUT_SEARCH_DATESCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검색문자열을 입력해주십시오..
        /// </summary>
        internal static string MSG_INPUT_SEARCH_STRING {
            get {
                return ResourceManager.GetString("MSG_INPUT_SEARCH_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 전송일시를 정확히 입력해주세요..
        /// </summary>
        internal static string MSG_INPUT_SEND_DATE {
            get {
                return ResourceManager.GetString("MSG_INPUT_SEND_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 업데이트내용를 입력해주십시오..
        /// </summary>
        internal static string MSG_INPUT_UPDATE_MEMO {
            get {
                return ResourceManager.GetString("MSG_INPUT_UPDATE_MEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 업데이트버전을 입력해주십시오..
        /// </summary>
        internal static string MSG_INPUT_UPDATE_VERSION {
            get {
                return ResourceManager.GetString("MSG_INPUT_UPDATE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록자ID에 특수문자가 존재합니다..
        /// </summary>
        internal static string MSG_LOGINID_EXIST_SPEC {
            get {
                return ResourceManager.GetString("MSG_LOGINID_EXIST_SPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 로그 내역.
        /// </summary>
        internal static string MSG_LOG_HISTORY {
            get {
                return ResourceManager.GetString("MSG_LOG_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메모저장중 예상치않은 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_MEMO_REG_ERROR {
            get {
                return ResourceManager.GetString("MSG_MEMO_REG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메모내용이 정확히 저장되었습니다..
        /// </summary>
        internal static string MSG_MEMO_REG_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_MEMO_REG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메시지 내용에 특수문자가 들어 있습니다. 다시 입력해주십시오..
        /// </summary>
        internal static string MSG_MESSAGE_SPEC_EXIST {
            get {
                return ResourceManager.GetString("MSG_MESSAGE_SPEC_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록자명에 특수문자가 존재합니다..
        /// </summary>
        internal static string MSG_NICKNAME_EXIST_SPEC {
            get {
                return ResourceManager.GetString("MSG_NICKNAME_EXIST_SPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록된 기기가 없습니다..
        /// </summary>
        internal static string MSG_NO_REG_DEVICE {
            get {
                return ResourceManager.GetString("MSG_NO_REG_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비밀번호를 변경하던중 예상치않은 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_PASSWORD_CHANGE_ERROR {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_CHANGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비밀번호를 정확히 변경하였습니다..
        /// </summary>
        internal static string MSG_PASSWORD_CHANGE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_CHANGE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 총 {0}개 디바이스중 {1}개 디바이스에 푸시 알림 메시지를 보냈습니다..
        /// </summary>
        internal static string MSG_PUSH_SEND_CONFIRM {
            get {
                return ResourceManager.GetString("MSG_PUSH_SEND_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택하신 QR코드가 이미 발급되였기때문에 수정할수 없습니다..
        /// </summary>
        internal static string MSG_QRCODE_ALREADY_AUTH {
            get {
                return ResourceManager.GetString("MSG_QRCODE_ALREADY_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 발급할 QR코드번호를 선택해주십시오..
        /// </summary>
        internal static string MSG_QRCODE_AUTH_CHECK {
            get {
                return ResourceManager.GetString("MSG_QRCODE_AUTH_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택한 시리얼번호가 정확히 발급되였습니다.\n발급한 시리얼 목록에서 확인하실수 있습니다..
        /// </summary>
        internal static string MSG_QRCODE_AUTH_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_QRCODE_AUTH_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR코드번호수정중 예상치않은 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_QRCODE_CHANGE_ERROR {
            get {
                return ResourceManager.GetString("MSG_QRCODE_CHANGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR코드번호정보가 정확히 수정되었습니다..
        /// </summary>
        internal static string MSG_QRCODE_CHANGE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_QRCODE_CHANGE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR코드번호생성중 예상치않은 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_QRCODE_CREATE_ERROR {
            get {
                return ResourceManager.GetString("MSG_QRCODE_CREATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR코드번호생성이 완료되었습니다. &lt;br&gt;&lt;br&gt; 생성한 QR코드목록에서 확인하실수 있습니다..
        /// </summary>
        internal static string MSG_QRCODE_CREATE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_QRCODE_CREATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 삭제할 QR코드번호를 선택해주십시오..
        /// </summary>
        internal static string MSG_QRCODE_DELETE_CHECK {
            get {
                return ResourceManager.GetString("MSG_QRCODE_DELETE_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR코드번호삭제중 예상치않은 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_QRCODE_DELETE_ERROR {
            get {
                return ResourceManager.GetString("MSG_QRCODE_DELETE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택한 QR코드번호가 정확히 삭제되었습니다. &lt;br&gt;&lt;br&gt;.
        /// </summary>
        internal static string MSG_QRCODE_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_QRCODE_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR코드상태 수정중 예상치않은 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_QRCODE_DETAIL_CHANGE_ERROR {
            get {
                return ResourceManager.GetString("MSG_QRCODE_DETAIL_CHANGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR코드번호정보 조회중 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_QRCODE_LISTING_ERROR {
            get {
                return ResourceManager.GetString("MSG_QRCODE_LISTING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR코드가 존재하지 않습니다..
        /// </summary>
        internal static string MSG_QRCODE_NO_EXIST {
            get {
                return ResourceManager.GetString("MSG_QRCODE_NO_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xls파일로 인쇄할 QR코드번호를 선택해주십시오..
        /// </summary>
        internal static string MSG_QRCODE_SAVE_CHECK {
            get {
                return ResourceManager.GetString("MSG_QRCODE_SAVE_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 전체 리스트 저장.
        /// </summary>
        internal static string MSG_SAVE_ALL_LIST {
            get {
                return ResourceManager.GetString("MSG_SAVE_ALL_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 표시된 리스트만 저장.
        /// </summary>
        internal static string MSG_SAVE_CURRENT_LIST {
            get {
                return ResourceManager.GetString("MSG_SAVE_CURRENT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 업데이트정보를 정확히 추가하였습니다..
        /// </summary>
        internal static string MSG_UPDATE_INFO_ADD_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_UPDATE_INFO_ADD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 업데이트정보삭제중 예상치않은 오류가 발생하였습니다..
        /// </summary>
        internal static string MSG_UPDATE_INFO_DELETE_ERROR {
            get {
                return ResourceManager.GetString("MSG_UPDATE_INFO_DELETE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 입력한 업데이트버전이 이미 존재합니다..
        /// </summary>
        internal static string MSG_UPDATE_INFO_EXIST {
            get {
                return ResourceManager.GetString("MSG_UPDATE_INFO_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (주의:파일 업로드시 zip파일만 등록 가능합니다. 용량제한 100M).
        /// </summary>
        internal static string MSG_UPLOAD_WARNING {
            get {
                return ResourceManager.GetString("MSG_UPLOAD_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 잘못된 접근입니다..
        /// </summary>
        internal static string MSG_WRONG_ACCESS {
            get {
                return ResourceManager.GetString("MSG_WRONG_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 계정추가.
        /// </summary>
        internal static string STR_ACCOUNT_ADD {
            get {
                return ResourceManager.GetString("STR_ACCOUNT_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 계정수정.
        /// </summary>
        internal static string STR_ACCOUNT_CHANGE {
            get {
                return ResourceManager.GetString("STR_ACCOUNT_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 계정권한.
        /// </summary>
        internal static string STR_ACCOUNT_LEVEL {
            get {
                return ResourceManager.GetString("STR_ACCOUNT_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 계정목록.
        /// </summary>
        internal static string STR_ACCOUNT_LIST {
            get {
                return ResourceManager.GetString("STR_ACCOUNT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 계정관리.
        /// </summary>
        internal static string STR_ACCOUNT_MANAGE {
            get {
                return ResourceManager.GetString("STR_ACCOUNT_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 활성화.
        /// </summary>
        internal static string STR_ACT {
            get {
                return ResourceManager.GetString("STR_ACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 활성화 됨.
        /// </summary>
        internal static string STR_ACTIVATED {
            get {
                return ResourceManager.GetString("STR_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 추 가.
        /// </summary>
        internal static string STR_ADD {
            get {
                return ResourceManager.GetString("STR_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 최고 관리자.
        /// </summary>
        internal static string STR_ADMINISTRATOR {
            get {
                return ResourceManager.GetString("STR_ADMINISTRATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 알 림.
        /// </summary>
        internal static string STR_ALERT {
            get {
                return ResourceManager.GetString("STR_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 전 체.
        /// </summary>
        internal static string STR_ALL {
            get {
                return ResourceManager.GetString("STR_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 총 디바이스 수.
        /// </summary>
        internal static string STR_ALL_DEVICE_NUMBER {
            get {
                return ResourceManager.GetString("STR_ALL_DEVICE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 전체 기기 등록수.
        /// </summary>
        internal static string STR_ALL_REG_DEVICE_NUMBER {
            get {
                return ResourceManager.GetString("STR_ALL_REG_DEVICE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 적용 가능한 기기 수.
        /// </summary>
        internal static string STR_APPLY_COUNT {
            get {
                return ResourceManager.GetString("STR_APPLY_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 적용 기기 정보.
        /// </summary>
        internal static string STR_APPLY_DEVICE_INFO {
            get {
                return ResourceManager.GetString("STR_APPLY_DEVICE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APP설정.
        /// </summary>
        internal static string STR_APP_SETTING {
            get {
                return ResourceManager.GetString("STR_APP_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 앱 업데이트.
        /// </summary>
        internal static string STR_APP_UPDATE {
            get {
                return ResourceManager.GetString("STR_APP_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 발 급.
        /// </summary>
        internal static string STR_AUTH {
            get {
                return ResourceManager.GetString("STR_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 발급한 QR코드목록.
        /// </summary>
        internal static string STR_AUTHED_QRCODE_LIST {
            get {
                return ResourceManager.GetString("STR_AUTHED_QRCODE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 발급확인.
        /// </summary>
        internal static string STR_AUTH_CONFIRM {
            get {
                return ResourceManager.GetString("STR_AUTH_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 발급날자.
        /// </summary>
        internal static string STR_AUTH_DATE {
            get {
                return ResourceManager.GetString("STR_AUTH_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 발급개수.
        /// </summary>
        internal static string STR_AUTH_NUMBER {
            get {
                return ResourceManager.GetString("STR_AUTH_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인증상태.
        /// </summary>
        internal static string STR_AUTH_STATUS {
            get {
                return ResourceManager.GetString("STR_AUTH_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 배너광고.
        /// </summary>
        internal static string STR_BANNER {
            get {
                return ResourceManager.GetString("STR_BANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 배너이미지.
        /// </summary>
        internal static string STR_BANNER_IMAGE {
            get {
                return ResourceManager.GetString("STR_BANNER_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 배너링크.
        /// </summary>
        internal static string STR_BANNER_LINK {
            get {
                return ResourceManager.GetString("STR_BANNER_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메인 배너 관리.
        /// </summary>
        internal static string STR_BANNER_MANAGE {
            get {
                return ResourceManager.GetString("STR_BANNER_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 배너명.
        /// </summary>
        internal static string STR_BANNER_NAME {
            get {
                return ResourceManager.GetString("STR_BANNER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 배너상태.
        /// </summary>
        internal static string STR_BANNER_STATUS {
            get {
                return ResourceManager.GetString("STR_BANNER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (주의: 가로512픽셀, 세로910픽셀 이하 이미지( JPG, PNG )만 등록 가능합니다.).
        /// </summary>
        internal static string STR_BANNER_WARNING {
            get {
                return ResourceManager.GetString("STR_BANNER_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse.
        /// </summary>
        internal static string STR_BROWSE {
            get {
                return ResourceManager.GetString("STR_BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 바이트.
        /// </summary>
        internal static string STR_BYTE {
            get {
                return ResourceManager.GetString("STR_BYTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 취 소.
        /// </summary>
        internal static string STR_CANCEL {
            get {
                return ResourceManager.GetString("STR_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 수 정.
        /// </summary>
        internal static string STR_CHANGE {
            get {
                return ResourceManager.GetString("STR_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 중국어.
        /// </summary>
        internal static string STR_CHINESE {
            get {
                return ResourceManager.GetString("STR_CHINESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확 인.
        /// </summary>
        internal static string STR_CONFIRM {
            get {
                return ResourceManager.GetString("STR_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 페지당표시수.
        /// </summary>
        internal static string STR_COUNT_PER_PAGE {
            get {
                return ResourceManager.GetString("STR_COUNT_PER_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 생성하기.
        /// </summary>
        internal static string STR_CREATE {
            get {
                return ResourceManager.GetString("STR_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 생성한 QR코드목록.
        /// </summary>
        internal static string STR_CREATED_QRCODE_LIST {
            get {
                return ResourceManager.GetString("STR_CREATED_QRCODE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 생성확인.
        /// </summary>
        internal static string STR_CREATE_CONFIRM {
            get {
                return ResourceManager.GetString("STR_CREATE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 생성날자.
        /// </summary>
        internal static string STR_CREATE_DATE {
            get {
                return ResourceManager.GetString("STR_CREATE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 생성개수.
        /// </summary>
        internal static string STR_CREATE_NUMBER {
            get {
                return ResourceManager.GetString("STR_CREATE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 생성 프로세스.
        /// </summary>
        internal static string STR_CREATE_PROCESS {
            get {
                return ResourceManager.GetString("STR_CREATE_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 발급인.
        /// </summary>
        internal static string STR_CREATOR {
            get {
                return ResourceManager.GetString("STR_CREATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (클라우드).
        /// </summary>
        internal static string STR_DATA_CLOUD {
            get {
                return ResourceManager.GetString("STR_DATA_CLOUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터설명.
        /// </summary>
        internal static string STR_DATA_DESCRIPTION {
            get {
                return ResourceManager.GetString("STR_DATA_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터식별코드.
        /// </summary>
        internal static string STR_DATA_ID {
            get {
                return ResourceManager.GetString("STR_DATA_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터링크.
        /// </summary>
        internal static string STR_DATA_LINK {
            get {
                return ResourceManager.GetString("STR_DATA_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터목록.
        /// </summary>
        internal static string STR_DATA_LIST {
            get {
                return ResourceManager.GetString("STR_DATA_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터관리.
        /// </summary>
        internal static string STR_DATA_MANAGE {
            get {
                return ResourceManager.GetString("STR_DATA_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터용량.
        /// </summary>
        internal static string STR_DATA_SIZE {
            get {
                return ResourceManager.GetString("STR_DATA_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터타입.
        /// </summary>
        internal static string STR_DATA_TYPE {
            get {
                return ResourceManager.GetString("STR_DATA_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터버전.
        /// </summary>
        internal static string STR_DATA_VERSION {
            get {
                return ResourceManager.GetString("STR_DATA_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 일.
        /// </summary>
        internal static string STR_DAY {
            get {
                return ResourceManager.GetString("STR_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 일간통계.
        /// </summary>
        internal static string STR_DAY_STAT {
            get {
                return ResourceManager.GetString("STR_DAY_STAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 삭 제.
        /// </summary>
        internal static string STR_DELETE {
            get {
                return ResourceManager.GetString("STR_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 삭제확인.
        /// </summary>
        internal static string STR_DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("STR_DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 상 세.
        /// </summary>
        internal static string STR_DETAIL {
            get {
                return ResourceManager.GetString("STR_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMEI번호.
        /// </summary>
        internal static string STR_DEVICE_IMEI {
            get {
                return ResourceManager.GetString("STR_DEVICE_IMEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 디바이스명.
        /// </summary>
        internal static string STR_DEVICE_NAME {
            get {
                return ResourceManager.GetString("STR_DEVICE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS버전.
        /// </summary>
        internal static string STR_DEVICE_OS_VERSION {
            get {
                return ResourceManager.GetString("STR_DEVICE_OS_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 엑셀로 다운로드.
        /// </summary>
        internal static string STR_DOWNLOAD_EXCEL {
            get {
                return ResourceManager.GetString("STR_DOWNLOAD_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 환경설정.
        /// </summary>
        internal static string STR_ENV_SETTING {
            get {
                return ResourceManager.GetString("STR_ENV_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이벤트.
        /// </summary>
        internal static string STR_EVENT {
            get {
                return ResourceManager.GetString("STR_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 즉시전송.
        /// </summary>
        internal static string STR_FAST_SEND {
            get {
                return ResourceManager.GetString("STR_FAST_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 최초기기등록날자.
        /// </summary>
        internal static string STR_FIRST_DEVICE_REG_DATE {
            get {
                return ResourceManager.GetString("STR_FIRST_DEVICE_REG_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 개.
        /// </summary>
        internal static string STR_GAE {
            get {
                return ResourceManager.GetString("STR_GAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시.
        /// </summary>
        internal static string STR_HOUR {
            get {
                return ResourceManager.GetString("STR_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정보수정.
        /// </summary>
        internal static string STR_INFO_CHANGE {
            get {
                return ResourceManager.GetString("STR_INFO_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 조선어.
        /// </summary>
        internal static string STR_KOREAN {
            get {
                return ResourceManager.GetString("STR_KOREAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 언어설정.
        /// </summary>
        internal static string STR_LANG_SETTING {
            get {
                return ResourceManager.GetString("STR_LANG_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License 관리자.
        /// </summary>
        internal static string STR_LICENSER {
            get {
                return ResourceManager.GetString("STR_LICENSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (10자 제한).
        /// </summary>
        internal static string STR_LIMIT_10 {
            get {
                return ResourceManager.GetString("STR_LIMIT_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (200자 제한).
        /// </summary>
        internal static string STR_LIMIT_200 {
            get {
                return ResourceManager.GetString("STR_LIMIT_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (50자 제한).
        /// </summary>
        internal static string STR_LIMIT_50 {
            get {
                return ResourceManager.GetString("STR_LIMIT_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 로그인.
        /// </summary>
        internal static string STR_LOGIN {
            get {
                return ResourceManager.GetString("STR_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록자ID.
        /// </summary>
        internal static string STR_LOGINID {
            get {
                return ResourceManager.GetString("STR_LOGINID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 자동로그인.
        /// </summary>
        internal static string STR_LOGIN_AUTOLOGIN {
            get {
                return ResourceManager.GetString("STR_LOGIN_AUTOLOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이디.
        /// </summary>
        internal static string STR_LOGIN_ID {
            get {
                return ResourceManager.GetString("STR_LOGIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이디저장.
        /// </summary>
        internal static string STR_LOGIN_IDSAVE {
            get {
                return ResourceManager.GetString("STR_LOGIN_IDSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /img/logo_ko.png.
        /// </summary>
        internal static string STR_LOGIN_LOGO {
            get {
                return ResourceManager.GetString("STR_LOGIN_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 패스워드.
        /// </summary>
        internal static string STR_LOGIN_PWD {
            get {
                return ResourceManager.GetString("STR_LOGIN_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 본 서비스를 리용하시려면 로그인 하셔야 합니다..
        /// </summary>
        internal static string STR_LOGIN_TITLE {
            get {
                return ResourceManager.GetString("STR_LOGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 로그아웃.
        /// </summary>
        internal static string STR_LOGOUT {
            get {
                return ResourceManager.GetString("STR_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 로그관리.
        /// </summary>
        internal static string STR_LOG_MANAGE {
            get {
                return ResourceManager.GetString("STR_LOG_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메 모.
        /// </summary>
        internal static string STR_MEMO {
            get {
                return ResourceManager.GetString("STR_MEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메세지 내용.
        /// </summary>
        internal static string STR_MESSAGE_CONTENT {
            get {
                return ResourceManager.GetString("STR_MESSAGE_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메세지 타이틀.
        /// </summary>
        internal static string STR_MESSAGE_TITLE {
            get {
                return ResourceManager.GetString("STR_MESSAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 분.
        /// </summary>
        internal static string STR_MINUTE {
            get {
                return ResourceManager.GetString("STR_MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 월.
        /// </summary>
        internal static string STR_MONTH {
            get {
                return ResourceManager.GetString("STR_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 윌/일/시.
        /// </summary>
        internal static string STR_MONTH_DAY_TIME {
            get {
                return ResourceManager.GetString("STR_MONTH_DAY_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 월간통계.
        /// </summary>
        internal static string STR_MONTH_STAT {
            get {
                return ResourceManager.GetString("STR_MONTH_STAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메시지 내용은 50자 이상 입력하실수 없습니다..
        /// </summary>
        internal static string STR_MSG_CONTENT_50_LIMIT {
            get {
                return ResourceManager.GetString("STR_MSG_CONTENT_50_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 메시지 타이틀은 50자 이상 입력하실수 없습니다..
        /// </summary>
        internal static string STR_MSG_TITLE_50_LIMIT {
            get {
                return ResourceManager.GetString("STR_MSG_TITLE_50_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 내 계정.
        /// </summary>
        internal static string STR_MY_ACCOUNT {
            get {
                return ResourceManager.GetString("STR_MY_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 내 계정 정보.
        /// </summary>
        internal static string STR_MY_ACCOUNT_INFO {
            get {
                return ResourceManager.GetString("STR_MY_ACCOUNT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록자명.
        /// </summary>
        internal static string STR_NICKNAME {
            get {
                return ResourceManager.GetString("STR_NICKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아 니.
        /// </summary>
        internal static string STR_NO {
            get {
                return ResourceManager.GetString("STR_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비활성화.
        /// </summary>
        internal static string STR_NO_ACT {
            get {
                return ResourceManager.GetString("STR_NO_ACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비활성화 됨.
        /// </summary>
        internal static string STR_NO_ACTIVATED {
            get {
                return ResourceManager.GetString("STR_NO_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 패스워드.
        /// </summary>
        internal static string STR_PASSWORD {
            get {
                return ResourceManager.GetString("STR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 패스워드변경.
        /// </summary>
        internal static string STR_PASSWORD_CHANGE {
            get {
                return ResourceManager.GetString("STR_PASSWORD_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 패스워드 확인.
        /// </summary>
        internal static string STR_PASSWORD_CONFIRM {
            get {
                return ResourceManager.GetString("STR_PASSWORD_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 제품타입.
        /// </summary>
        internal static string STR_PRODUCT_TYPE {
            get {
                return ResourceManager.GetString("STR_PRODUCT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 푸시알람.
        /// </summary>
        internal static string STR_PUSH_ALARM {
            get {
                return ResourceManager.GetString("STR_PUSH_ALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUSH 알림 내역.
        /// </summary>
        internal static string STR_PUSH_LIST {
            get {
                return ResourceManager.GetString("STR_PUSH_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 푸시 보내기.
        /// </summary>
        internal static string STR_PUSH_SEND {
            get {
                return ResourceManager.GetString("STR_PUSH_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR코드발급.
        /// </summary>
        internal static string STR_QRCODE_AUTH {
            get {
                return ResourceManager.GetString("STR_QRCODE_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR코드생성수량.
        /// </summary>
        internal static string STR_QRCODE_COUNT {
            get {
                return ResourceManager.GetString("STR_QRCODE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR코드 생성.
        /// </summary>
        internal static string STR_QRCODE_CREATE {
            get {
                return ResourceManager.GetString("STR_QRCODE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR코드 삭제.
        /// </summary>
        internal static string STR_QRCODE_DELETE {
            get {
                return ResourceManager.GetString("STR_QRCODE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR코드정보.
        /// </summary>
        internal static string STR_QRCODE_INFO {
            get {
                return ResourceManager.GetString("STR_QRCODE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR코드관리.
        /// </summary>
        internal static string STR_QRCODE_MANAGE {
            get {
                return ResourceManager.GetString("STR_QRCODE_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR코드번호.
        /// </summary>
        internal static string STR_QRCODE_NUMBER {
            get {
                return ResourceManager.GetString("STR_QRCODE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 실제품.
        /// </summary>
        internal static string STR_REAL_PRODUCT {
            get {
                return ResourceManager.GetString("STR_REAL_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록날자.
        /// </summary>
        internal static string STR_REG_DATE {
            get {
                return ResourceManager.GetString("STR_REG_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록된 기기수.
        /// </summary>
        internal static string STR_REG_DEVICE_COUNT {
            get {
                return ResourceManager.GetString("STR_REG_DEVICE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 예약되었습니다..
        /// </summary>
        internal static string STR_RESERVATION {
            get {
                return ResourceManager.GetString("STR_RESERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 저 장.
        /// </summary>
        internal static string STR_SAVE {
            get {
                return ResourceManager.GetString("STR_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 저장확인.
        /// </summary>
        internal static string STR_SAVE_CONFIRM {
            get {
                return ResourceManager.GetString("STR_SAVE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 엑셀로 저장.
        /// </summary>
        internal static string STR_SAVE_EXCEL {
            get {
                return ResourceManager.GetString("STR_SAVE_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 범위설정.
        /// </summary>
        internal static string STR_SCALE_SETTING {
            get {
                return ResourceManager.GetString("STR_SCALE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검 색.
        /// </summary>
        internal static string STR_SEARCH {
            get {
                return ResourceManager.GetString("STR_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 보내기.
        /// </summary>
        internal static string STR_SEND {
            get {
                return ResourceManager.GetString("STR_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 보낸 디바이스 수.
        /// </summary>
        internal static string STR_SENDED_DEVICE_NUMBER {
            get {
                return ResourceManager.GetString("STR_SENDED_DEVICE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 발송일자.
        /// </summary>
        internal static string STR_SEND_DATE {
            get {
                return ResourceManager.GetString("STR_SEND_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 전송완료.
        /// </summary>
        internal static string STR_SEND_END {
            get {
                return ResourceManager.GetString("STR_SEND_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 전송대기.
        /// </summary>
        internal static string STR_SEND_WAITING {
            get {
                return ResourceManager.GetString("STR_SEND_WAITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버접속주기.
        /// </summary>
        internal static string STR_SERVER_CONNECT_CYCLE {
            get {
                return ResourceManager.GetString("STR_SERVER_CONNECT_CYCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설 정.
        /// </summary>
        internal static string STR_SETTING {
            get {
                return ResourceManager.GetString("STR_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 예약전송.
        /// </summary>
        internal static string STR_SLOW_SEND {
            get {
                return ResourceManager.GetString("STR_SLOW_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통 계.
        /// </summary>
        internal static string STR_STAT {
            get {
                return ResourceManager.GetString("STR_STAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통계현황.
        /// </summary>
        internal static string STR_STATISTICS {
            get {
                return ResourceManager.GetString("STR_STATISTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 상 태.
        /// </summary>
        internal static string STR_STATUS {
            get {
                return ResourceManager.GetString("STR_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 합 계.
        /// </summary>
        internal static string STR_SUM {
            get {
                return ResourceManager.GetString("STR_SUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시험제품.
        /// </summary>
        internal static string STR_TEST_PRODUCT {
            get {
                return ResourceManager.GetString("STR_TEST_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “옷AR” 관리자페지.
        /// </summary>
        internal static string STR_TITLE {
            get {
                return ResourceManager.GetString("STR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 업데이트내역.
        /// </summary>
        internal static string STR_UPDATE_INFO {
            get {
                return ResourceManager.GetString("STR_UPDATE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 업데이트버전.
        /// </summary>
        internal static string STR_UPDATE_VERSION {
            get {
                return ResourceManager.GetString("STR_UPDATE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사용한 QR코드 수.
        /// </summary>
        internal static string STR_USED_QRCODE_NUMBER {
            get {
                return ResourceManager.GetString("STR_USED_QRCODE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 년.
        /// </summary>
        internal static string STR_YEAR {
            get {
                return ResourceManager.GetString("STR_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 년간통계.
        /// </summary>
        internal static string STR_YEAR_STAT {
            get {
                return ResourceManager.GetString("STR_YEAR_STAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 예.
        /// </summary>
        internal static string STR_YES {
            get {
                return ResourceManager.GetString("STR_YES", resourceCulture);
            }
        }
    }
}
